name: New Dataset
description: Ingest and publish data to the VEDA data store & STAC API
title: "New Dataset: <dataset title>"
labels: ['dataset']

body:
  - type: markdown
    attributes:
      value: |
        Use this form to make sure that you are providing enough information about the data.
        For detailed guidance on how to set up a dataset for ingestion take a look at the
        [VEDA docs on Data Ingestion](https://nasa-impact.github.io/veda-docs/contributing/dataset-ingestion/).
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Who should we be giving updates to and asking for any additional information from?
      placeholder: ex. email@nasa.gov
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL/DOI
      description: If applicable, what is the DOI or URL associated with this dataset?
    validations:
      required: false
  - type: input
    id: license
    attributes:
      label: Data License
      description: What license is the data available under?
      placeholder: CC-0
    validations:
      required: false
  - type: input
    id: data-location
    attributes:
      label: Data Location
      description: Where is the data currently stored?
      placeholder: ex. s3://veda-data-store-staging/no2-monthly-diff
    validations:
      required: true
  - type: input
    id: size-estimate
    attributes:
      label: Size Estimate
      description: Roughly how much data is in the dataset (in terms of GB/TB/PB)?
    validations:
      required: false
  - type: input
    id: n-items
    attributes:
      label: Number of Items
      description: How many items are in this directory/bucket?
    validations:
      required: false
  - type: input
    id: description
    attributes:
      label: Description
      description: Please provide a short description of the data.
    validations:
      required: true
  - type: input
    id: collection
    attributes:
      label: Collection Creation Notebook
      description: |
        Link to the notebook where you are creating a valid STAC collection following the example in
        [VEDA docs on Collection Creation](https://nasa-impact.github.io/veda-docs/notebooks/veda-operations/stac-collection-creation.html).
        Any type of link is fine: a github gist, a notebooksharing.space link,
        a link to a shared version of the notebook on one of the jupyter hubs, ...
    validations:
      required: false
  - type: input
    id: item
    attributes:
      label: Item Creation Notebook
      description: |
        Link to the notebook where you are creating a valid STAC item following the
        [VEDA docs on Item Creation](https://nasa-impact.github.io/veda-docs/notebooks/veda-operations/stac-item-creation.html).
        Any type of link is fine: a github gist, a notebooksharing.space link,
        a link to a shared version of the notebook on one of the jupyter hubs, ...
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Use the following checklist to ensure your data is valid.
      options:
        - label: "Files are valid COGs. Use [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation)"
          required: false
        - label: "COGs appear to be correct"
          required: false
  - type: textarea
    id: extra
    attributes:
      label: Any additional info you think is relevant, possibly including spatial or temporal subset if applicable?
    validations:
      required: false
  - type: checkboxes
    id: tasks
    attributes:
      label: To Do
      description: This section is for the VEDA team to track progress. You can leave it blank.
      options:
        - label: "Open PR for publishing those datasets to the Staging API"
          required: false
        - label: "Notify QA / move ticket to QA state"
          required: false
        - label: "Once approved, merge and close"
          required: false
