name: Data promotion request
description: Request to publish staged STAC Collection to production.
title: "[Collection ID]: "
labels: ["publication"]
projects: ["NASA-IMPACT/veda-data"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to the VEDA STAC catalog!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: data-host
    attributes:
      label: Data Host
      description: Will the S3 object be hosted in the VEDA data store or an external account?
      options:
        - VEDA Data Store
        - Landsat DAAC
        - ORNL DAAC
        - MAAP
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: staged-collection
    attributes:
      label: Staged STAC Collection
      description: Id of the STAC collection in staging.openveda.cloud/api/stac/collections to promote.
      placeholder: no2-monthly
    validations:
      required: true
  - type: textarea
    id: discovery-config
    attributes:
      label: Where can the S3 files be found?
      description: Please provide workflow configuration used to discover the items for your collection
      placeholder: Tell us what you see!
      value: "{
        "collection": "<coll_name>",
        "bucket": "<bucket>",
        "prefix": "<prefix>/",
        "filename_regex": "<file_regex>",
        "id_regex": "<id_regex>",
        "id_template": "<id_template_string>",
        "datetime_range": "<year>|<month>|<day>",
        "assets": {
            "<asset1_name>": {
                "title": "<asset_title>",
                "description": "<asset_description>",
                "regex": "<asset_regex>"
            },
            "<asset2_name>": {
                "title": "<asset_title>",
                "description": "<asset_description>",
                "regex": "<asset_regex>"
            }
        }
    }"
    validations:
      required: true
