name: Test promotion script

on:
  push:
    branches: ['feat/airflow3-flag']
    paths:
      # Run the workflow only if files inside this path are updated
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/test-promotion-script.yml'

jobs:
  test-promotion-script:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r ./scripts/requirements.txt

      - name: Test promotion script (Airflow 3)
        env:
            STAGING_SM2A_API_URL: ${{ vars.TESTING_AIRFLOW3_SM2A_API_URL }}
            STAGING_SM2A_ADMIN_USERNAME: ${{ secrets.TESTING_AIRFLOW3_SM2A_ADMIN_USERNAME}}
            STAGING_SM2A_ADMIN_PASSWORD: ${{ secrets.TESTING_AIRFLOW3_SM2A_ADMIN_PASSWORD}}
            STAGING_AIRFLOW_API_VERSION: "3"
            KEYCLOAK_URL: ${{ vars.KEYCLOAK_URL }}
            KEYCLOAK_REALM: ${{ vars.KEYCLOAK_REALM }}
            KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
            KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            PYTHONPATH: .
        run: |
          response=$(python3 scripts/promote_collection.py tests/test_collection.json staging)
          status_code=$(echo "$response" | jq -r '.statusCode' | head -n1)
              echo "Status Code: $status_code"

              # Update status message based on response code
              if [[ $status_code -eq 200 ]] || [[ $status_code -eq 201 ]]; then
                echo "Airflow 3 test passed"
              else
                echo "$collection_id failed to publish ❌"
                exit 1
              fi

      - name: Test promotion script (Airflow 2)
        env:
            STAGING_SM2A_API_URL: ${{ vars.TESTING_AIRFLOW2_SM2A_API_URL }}
            STAGING_SM2A_ADMIN_USERNAME: ${{ secrets.TESTING_AIRFLOW2_SM2A_ADMIN_USERNAME}}
            STAGING_SM2A_ADMIN_PASSWORD: ${{ secrets.TESTING_AIRFLOW2_SM2A_ADMIN_PASSWORD}}
            STAGING_AIRFLOW_API_VERSION: "2"
            PYTHONPATH: .
        run: |
          python3 scripts/promote_collection.py tests/test_collection_tenant.json staging
          response=$(python3 scripts/promote_collection.py tests/test_collection_tenant.json staging)
          status_code=$(echo "$response" | jq -r '.statusCode' | head -n1)
              echo "Status Code: $status_code"

              # Update status message based on response code
              if [[ $status_code -eq 200 ]] || [[ $status_code -eq 201 ]]; then
                echo "Airflow 2 test passed"
              else
                echo "$collection_id failed to publish ❌"
                exit 1
              fi
